version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_service
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: easy-cooking
      POSTGRES_USER: huynv

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: